### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by jugglingnutcase** [pixel-glyph/LitList#1]
OK, i guess i'll start everything in one parent issue and then we can split off to more issues and PRs as we go?

First off, it looks great! Much better looking than something i would produce :smile_cat:. i especially like that the books have covers.

i've mostly looked at the app and how it works here. **Would you like a code review too?** Or was that the main thing you were looking for? Anyway, thoughts follow...

### Things i like

* the typography and look of the site, it looks really nice
* having book covers show up to select is a nice touch, i was pleasantly surprised by that feature
* the app is simple, which is helpful for understanding what it does after a quick glance (making it a nice thing to show)

### Some features i'd like to see

* i would like to see books i add and finish be persisted across closing and reopening the site! i'll bet you've already thought of this, but i think that would go a long way towards a better first impression. Loss of work is pretty jarring, even for a demo site.

### Suggestions

* i think you should switch branches to a `gh-pages` branch and use [GitHub Pages](http://pages.github.com/) to show off this project, especially since it only requires HTML/CSS/js. 

  All you need to do is create a gh-pages branch and work off of that and you'll have a site automatically created & updated for you.
* i think you should take a gander at how todo apps work. This reading list is very similar to a todo manager, maybe you can glean some ideas?
* have you explored front-end-design via node much? there's some nice things that the node environment offers for working with projects like these. i'm thinking mostly of [bower](http://bower.io/), but there's lots of other cool tools out there. i can make more recommendations if you're interested.

**Comment by jugglingnutcase** [comment]
i'll keep going, the above are just initial thoughts

### Other nice things

* Animations for moving books across columns
* Responsive! alright!

**Comment by pixel-glyph** [comment]
I was going to warn about the loss of data on a page refresh. Yes, that's the next thing I'm working on. Should I make it so a user's list is only saved locally, or should I do some database coding?

Github Pages sounds perfect! I was going to find a hosting service but perhaps I'll just use this.

**Comment by pixel-glyph** [comment]
Thanks for the input! Don't worry about a code review. I'm more concerned with whether the site is functional enough to be a presentable project. I'll check out Bower---it would be nice to add some node features.

**Comment by jugglingnutcase** [comment]
> Should I make it so a user's list is only saved locally, or should I do some database coding?

Up to you, but i'd suggest starting locally and building out database stuff from there if you're interested.

**Comment by jugglingnutcase** [comment]
[localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) would be a quick & easy way to do it.

**Comment by pixel-glyph** [comment]
I may have to use an alternative to localStorage. When trying to access stored data, [object, object] is returned. To resolve this, others recommend using JSON.stringify on storing data and then JSON.parse for accessing it. But JSON.stringify throws 'converting circular structure to json' TypeError. 

I think jQuery's [.data()](https://api.jquery.com/data/) might work.

**Comment by jugglingnutcase** [comment]
I wonder what's circular about your data, I would think that could be worked around. The stringify route is the way the go for localStorage. 

Maybe IndexedDB (term?) would be another option?

I may take a look out of curiosity. 

jamie

**Comment by pixel-glyph** [comment]
Just a heads up: I didn't push those changes. But this how I'm storing the data as a user adds a book:

    localStorage.setItem(title, JSON.stringify($('#toRead').children('li').eq(1)));

where 'title' is the html of the <p> tag containing the book's title, and
    
    $('#toRead').children('li').eq(1)

is the entire <li> tag that contains all the info for the most recently added book.

This might not be helpful without seeing the context.

**Comment by pixel-glyph** [comment]
Maybe it's considered circular because the title is in both the key and value? If that's the case, I'll try using some other value for the key.

**Comment by jugglingnutcase** [comment]
Mind if I give something a shot?

jamie

**Comment by pixel-glyph** [comment]
Not at all!
