### ISSUE TITLE
Are there supposed to be to read/finished modal links for the smaller screens?

### ISSUE THREAD

**Issue by jugglingnutcase** [pixel-glyph/LitList#2]
On desktop i can click on the headers and get modals for the lists... is that supposed to be available for smaller screens?

**Comment by pixel-glyph** [comment]
Nope, I disabled the single list modals for mobile view. Didn't think it was really necessary on smaller screens.

**Comment by jugglingnutcase** [comment]
Makes sense to me, just curious.
